#!/usr/bin/env python3
"""Generate guest D3D8 constants from the pinned Wine headers.

dx/d3d8_constants.json lists the constant names d3d8.cpp uses. Each is resolved
from `#define NAME expr` lines or `NAME = expr` enum members in the reference
headers and emitted as a constexpr uint32_t with the header's own name. A name
that is missing, ambiguous or not a plain integer expression fails generation
rather than falling back to a guessed value. --check verifies committed output.
"""
import argparse
import ast
import hashlib
import json
from pathlib import Path
import re

DEFINE = re.compile(r'^[ \t]*#[ \t]*define[ \t]+(\w+)[ \t]+(.+?)[ \t]*$', re.M)
MEMBER = re.compile(r'\s*(\w+)\s*(?:=\s*(.+?))?\s*', re.S)
ENUM = re.compile(r'typedef\s+enum\s+\w*\s*\{(.*?)\}', re.S)


def strip_comments(text):
    text = re.sub(r'/\*.*?\*/', ' ', text, flags=re.S)
    return re.sub(r'//[^\n]*', '', text)


def fourcc(a, b, c, d):
    return ord(a) | ord(b) << 8 | ord(c) << 16 | ord(d) << 24


def split_members(body):
    """Split an enum body on commas that are not inside parentheses."""
    items, depth, current = [], 0, ''
    for char in body:
        depth += char == '('
        depth -= char == ')'
        if char == ',' and depth == 0:
            items.append(current)
            current = ''
        else:
            current += char
    return items + [current]


def collect(headers):
    """Return {name: expression-or-None-for-implicit-enum-value}, rejecting redefinitions."""
    table = {}

    def add(name, value):
        if name in table and table[name] != value:
            raise ValueError('conflicting definitions of ' + name)
        table[name] = value

    for text in headers:
        text = strip_comments(text)
        for name, value in DEFINE.findall(text):
            add(name, value.strip())
        for body in ENUM.findall(text):
            previous = None
            for item in split_members(body):
                match = MEMBER.fullmatch(item)
                if not match or not match[1].startswith('D3D'):
                    continue
                name, value = match[1], match[2]
                if value is None:
                    if previous is None:
                        raise ValueError('enum member without value: ' + name)
                    value = f'({previous}) + 1'
                add(name, value.strip())
                previous = name
    return table


def evaluate(name, table, stack=()):
    if name in stack:
        raise ValueError('circular definition: ' + name)
    if name not in table:
        raise ValueError('undefined constant: ' + name)
    expr = re.sub(r'__MSABI_LONG\(((?:[^()]|\([^()]*\))*)\)', r'\1', table[name])
    expr = re.sub(r'\b(0x[0-9a-fA-F]+|\d+)[uUlL]+\b', r'\1', expr)
    expr = re.sub(r'MAKEFOURCC\s*\(', 'fourcc(', expr)

    def walk(node):
        if isinstance(node, ast.Expression):
            return walk(node.body)
        if isinstance(node, ast.Constant) and isinstance(node.value, int):
            return node.value
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            return node.value
        if isinstance(node, ast.Name):
            return evaluate(node.id, table, stack + (name,))
        if isinstance(node, ast.BinOp):
            ops = {ast.Add: lambda a, b: a + b, ast.Sub: lambda a, b: a - b,
                   ast.BitOr: lambda a, b: a | b, ast.BitAnd: lambda a, b: a & b,
                   ast.LShift: lambda a, b: a << b}
            if type(node.op) in ops:
                return ops[type(node.op)](walk(node.left), walk(node.right))
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id == 'fourcc':
            return fourcc(*[walk(arg) for arg in node.args])
        raise ValueError(f'{name}: unsupported expression {table[name]!r}')

    try:
        value = walk(ast.parse(expr.strip(), mode='eval'))
    except SyntaxError:
        raise ValueError(f'{name}: unsupported expression {table[name]!r}') from None
    if not isinstance(value, int) or not 0 <= value <= 0xFFFFFFFF:
        raise ValueError(f'{name}: not a 32-bit unsigned value')
    return value


def render(headers, names):
    if len(set(names)) != len(names):
        raise ValueError('duplicate constant name')
    for name in names:
        if not re.fullmatch(r'D3D[A-Z0-9_]+', name):
            raise ValueError('invalid constant name: ' + name)
    table = collect([header.decode('utf-8') for header in headers])
    digest = hashlib.sha256(b''.join(headers)).hexdigest()
    lines = ['// Generated by tools/gen_d3d8_constants.py; do not edit.',
             '// Reference SHA256 (concatenated headers): ' + digest, '']
    for name in names:
        value = f'0x{evaluate(name, table):08x}u'
        # The Rust ABI header already defines some of these as macros; keep it
        # honest by checking its value against the Wine header's.
        lines += [f'#ifdef {name}', f'static_assert({name} == {value}, "{name} differs from the Wine header");',
                  '#else', f'constexpr uint32_t {name} = {value};', '#endif']
    lines.append('')
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--reference', type=Path, nargs='+', required=True)
    parser.add_argument('--names', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    try:
        generated = render([path.read_bytes() for path in args.reference],
                           json.loads(args.names.read_text()))
        if args.check:
            if args.output.read_text() != generated:
                parser.error(str(args.output) + ' is stale; regenerate D3D8 constants')
        elif not args.output.exists() or args.output.read_text() != generated:
            args.output.write_text(generated)
    except (ValueError, OSError, KeyError) as failure:
        parser.error(str(failure))


if __name__ == '__main__':
    main()
