#!/usr/bin/env python3
"""Render games/<id>/game.toml into game_config.h and game_config.cmake.

    tools/gen_game_config.py --game-dir /abs/path/to/<game> --header OUT.h --cmake OUT.cmake

The header is what runtime/, dx/ and host/ include for every game-specific
value; the cmake fragment names the app and the image base for the build."""

import argparse
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
import game_config  # noqa: E402

STRINGS = (("id", "RECOMP_GAME_ID"), ("name", "RECOMP_GAME_NAME"), ("app_name", "RECOMP_APP_NAME"),
           ("bundle_id", "RECOMP_BUNDLE_ID"), ("executable", "RECOMP_EXECUTABLE"),
           ("sha256", "RECOMP_EXE_SHA256"), ("guest_root", "RECOMP_GUEST_ROOT"))
ADDRESSES = (("image_base", "RECOMP_IMAGE_BASE"), ("entry_point", "RECOMP_ENTRY_POINT"),
             ("heap_base", "RECOMP_HEAP_BASE"), ("heap_end", "RECOMP_HEAP_END"))

# Optional [hooks] the runtime, dx and hosts reference unconditionally. A game
# that does not hook one still has to compile, so absence renders a value that
# disables the feature rather than leaving the macro undefined. Zero names no
# real guest address and a one-entry cursor list pointing at address zero has
# no live surface to find, so both are safely inert. Hooks a game deliberately
# leaves out for compile-time guards (sprites) are not here: those stay
# undefined so `#ifdef RECOMP_HOOK_SPRITES_COUNT` keeps working.
HOOK_DEFAULTS = {
    "frame_clock_begin": 0,
    "frame_clock_wait": 0,
    "frame_clock_wait_clamp": 0,
    "frame_clock_clamp_deadline": 0,
    "frame_clock_wait_deadline": 0,
    "cursor_surface_ptrs": [0],
    "camera": 0,
}


def c_string(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def c_hex(value):
    return "0x%08xu" % value


def c_string_list(values):
    """A brace initializer of C strings ending in a null pointer."""
    return "{" + "".join(c_string(v) + ", " for v in values) + "0}"


def render_header(cfg):
    game = cfg["game"]
    lines = ["/* generated by tools/gen_game_config.py from %s -- do not edit */" % cfg["source"],
             "#pragma once"]
    for key, macro in STRINGS:
        lines.append("#define %s %s" % (macro, c_string(game[key])))
    for key, macro in ADDRESSES:
        lines.append("#define %s %s" % (macro, c_hex(game[key])))
    for field, value in zip(("MAJOR", "MINOR", "BUILD", "PLATFORM"),
                            game_config.windows_version(game["windows_version"])):
        lines.append("#define RECOMP_WINDOWS_%s %du" % (field, value))
    # Absolute: the developer's game lives beside game.toml, not under the kit.
    lines.append("#define RECOMP_DEVELOPER_EXE %s" % c_string(cfg["developer_exe_path"].as_posix()))
    lines.append("#define RECOMP_DEVELOPER_GAME_DIR %s" % c_string(cfg["developer_exe_path"].parent.as_posix()))
    lines.append("#define RECOMP_GAME_DIR %s" % c_string(Path(cfg["dir"]).resolve().as_posix()))
    lines.append("#define RECOMP_KIT_DIR %s" % c_string(Path(__file__).resolve().parents[1].as_posix()))
    # The on-screen controls a fresh profile starts with, and how the pad maps
    # onto the keyboard/mouse or a real controller (games/stub/game.toml [controls]).
    controls = cfg["controls"]
    lines.append("#define RECOMP_CONTROLS_DEFAULT_LAYOUT %s" % c_string(controls["default_layout"]))
    lines.append("#define RECOMP_CONTROLS_PAD %d" % ("off", "mapped", "native").index(controls["pad"]))
    lines.append("#define RECOMP_CONTROLS_MAPPED %s" % c_string(
        ";".join("%s=%s" % (k, controls["mapped"][k]) for k in sorted(controls["mapped"]))))
    native = controls["native"]
    lines.append("#define RECOMP_CONTROLS_XINPUT %d" % int(native["xinput"]))
    lines.append("#define RECOMP_CONTROLS_DINPUT %d" % int(native["dinput"]))
    lines.append("#define RECOMP_CONTROLS_NATIVE_AXES %s" % c_string(",".join(native["axes"])))
    lines.append("#define RECOMP_CONTROLS_NATIVE_BUTTONS %s" % c_string(",".join(native["buttons"])))
    lines.append("#define RECOMP_GUEST_SIZE %s" % c_hex(game["guest_size"]))
    lines.append("#define RECOMP_STRICT_IMPORTS %d" % int(game["strict_imports"]))
    lines.append("#define RECOMP_INPUT_RELATIVE_MOUSE_CAPTURE %d" % int(cfg["input"]["relative_mouse_capture"]))
    lines.append("#define RECOMP_CD_AUDIO_TRACKS %s" % c_string_list(cfg.get("media", {}).get("cd_tracks", [])))
    lines.append("#define RECOMP_AUX_MODULE_COUNT %d" % len(cfg["aux_modules"]))
    lines.append("#define RECOMP_AUX_MODULES {%s}" % ", ".join(
        "{%s, %s, %s, %s, %s}" % (c_string(m["name"]), c_string(m["path"].as_posix()),
                                 c_string(m["sha256"]), c_hex(m["base"]), c_hex(m["size"]))
        for m in cfg["aux_modules"]) if cfg["aux_modules"] else
        "#define RECOMP_AUX_MODULES {{0, 0, 0, 0u, 0u}}")
    # One bit per settings-page row, in game_config.SETTINGS_ROWS order.
    mask = sum(1 << i for i, row in enumerate(game_config.SETTINGS_ROWS) if row in cfg["settings"]["rows"])
    lines.append("#define RECOMP_SETTINGS_ROWS 0x%03xu" % mask)
    # The launcher's data: what to call the game, where to get it, where an
    # install may be, and what an import copies (host/launcher/).
    launcher = cfg["launcher"]
    lines.append("#define RECOMP_LAUNCHER_TITLE %s" % c_string(launcher["title"]))
    lines.append("#define RECOMP_LAUNCHER_STORE_URL %s" % c_string(launcher["store"]))
    lines.append("#define RECOMP_LAUNCHER_INSTALL_NAMES %s" % c_string_list(launcher["install_names"]))
    lines.append("#define RECOMP_LAUNCHER_GOG_IDS %s" % c_string_list(launcher["gog_ids"]))
    lines.append("#define RECOMP_LAUNCHER_STEAM_IDS %s" % c_string_list(launcher["steam_ids"]))
    lines.append("#define RECOMP_LAUNCHER_MIN_FREE_MB %du" % launcher["min_free_mb"])
    lines.append("#define RECOMP_REQUIRED_DIRS %s" % c_string_list(cfg["setup"]["required_dirs"]))
    lines.append("#define RECOMP_BUNDLE_EXCLUDE %s" % c_string_list(cfg["bundle"]["exclude"]))
    hooks = dict(HOOK_DEFAULTS)
    hooks.update(cfg.get("hooks", {}))
    for key, value in sorted(hooks.items()):
        macro = "RECOMP_HOOK_" + key.upper()
        if isinstance(value, list):
            lines.append("#define %s_COUNT %d" % (macro, len(value)))
            lines.append("#define %s {%s}" % (macro, ", ".join(c_hex(v) for v in value)))
        else:
            lines.append("#define %s %s" % (macro, c_hex(value)))
    for key, entry in sorted(cfg.get("globals", {}).items()):
        macro = "RECOMP_GLOBAL_" + key.upper()
        lines.append("#define %s_ADDR %s" % (macro, c_hex(entry["addr"])))
        for field in ("size", "stride", "count"):
            if field in entry:
                lines.append("#define %s_%s %du" % (macro, field.upper(), entry[field]))
    return "\n".join(lines) + "\n"


def render_cmake(cfg):
    game = cfg["game"]
    lines = ["# generated by tools/gen_game_config.py from %s -- do not edit" % cfg["source"]]
    for key, macro in STRINGS[:5]:
        lines.append('set(%s "%s")' % (macro, game[key]))
    lines.append("set(RECOMP_IMAGE_BASE %s)" % c_hex(game["image_base"]))
    lines.append("set(RECOMP_HEAP_BASE %s)" % c_hex(game["heap_base"]))
    lines.append("set(RECOMP_HEAP_END %s)" % c_hex(game["heap_end"]))
    lines.append("set(RECOMP_GUEST_SIZE %s)" % c_hex(game["guest_size"]))
    lines.append("set(RECOMP_AUX_MODULES %s)" % ";".join(m["key"] for m in cfg["aux_modules"]))
    lines.append("set(RECOMP_STORE_HOOKS %d)" % int(game["store_hooks"]))
    # The generated sources include this header before they define FN_<addr>,
    # which is how a game replaces one translated function with a native one.
    lines.append('set(RECOMP_OVERRIDE_HEADER "%s")'
                 % (cfg["overrides_header"].as_posix() if cfg.get("overrides_header") else ""))
    lines.append('set(RECOMP_DEVELOPER_GAME_DIR "%s")' % cfg["developer_exe_path"].parent.as_posix())
    lines.append('set(RECOMP_DEVELOPER_EXE "%s")' % cfg["developer_exe_path"].as_posix())
    # [translate] native: C replacements for hot functions, compiled with the
    # translation. The header #defines FN_<addr> to each replacement (see the
    # override note in funcs.h); the sources define them.
    native = cfg["translate"].get("native", {})
    game_dir = Path(cfg["dir"])
    if native.get("header"):
        lines.append('set(RECOMP_NATIVE_HEADER "%s")' % (game_dir / native["header"]).resolve().as_posix())
        sources = [(game_dir / s).resolve().as_posix() for s in native.get("sources", ())]
        lines.append('set(RECOMP_NATIVE_SOURCES "%s")' % ";".join(sources))
    return "\n".join(lines) + "\n"


def write_if_changed(path, text):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.is_file() or path.read_text() != text:
        path.write_text(text)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--game-dir", type=Path, required=True)
    parser.add_argument("--build-root", type=Path, default=None)
    parser.add_argument("--header", type=Path, required=True)
    parser.add_argument("--cmake", type=Path, required=True)
    args = parser.parse_args()
    cfg = game_config.load(args.game_dir, args.build_root)
    write_if_changed(args.header, render_header(cfg))
    write_if_changed(args.cmake, render_cmake(cfg))


if __name__ == "__main__":
    main()
