#!/usr/bin/env python3
"""Generate guest COM slot tables and IIDs from a pinned Wine API header.

The JSON supplies handler choices only. Names, order and stdcall arity (including
this) come from the header. Unsupported methods keep named import diagnostics.
This deliberately accepts the explicit, flattened STDMETHOD form in Wine headers;
unknown declarations or stale handler names fail rather than producing a partial
vtable. --check verifies committed output without modifying it.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import uuid


def render(reference, bindings):
    text = reference.decode('utf-8')
    lines = ['// Generated by tools/gen_com_interfaces.py; do not edit.',
             '// Reference SHA256: ' + hashlib.sha256(reference).hexdigest(), '']
    seen = set()
    for binding in bindings:
        name, table, symbol = (binding[key] for key in ('interface', 'table', 'iid'))
        if name in seen:
            raise ValueError('duplicate interface: ' + name)
        seen.add(name)
        for identifier in (name, table, symbol, *binding['handlers'].values()):
            if not re.fullmatch(r'[A-Za-z_][A-Za-z0-9_]*', identifier):
                raise ValueError('invalid C++ identifier: ' + identifier)
        declaration = re.search(r'DECLARE_INTERFACE_IID_\(' + re.escape(name) +
                                r',\s*\w+,\s*"([^"]+)"\)\s*\{(.*?)\n\};', text, re.S)
        if declaration is None:
            raise ValueError('missing interface: ' + name)
        iid = uuid.UUID(declaration[1]).bytes_le
        methods = []
        pattern = r'STDMETHOD(?:_\([^,]+,\s*(\w+)\s*\)|\(\s*(\w+)\s*\))\s*\((.*?)\)\s*PURE\s*;'
        body = declaration[2]
        for method in re.finditer(pattern, body, re.S):
            method_name = method[1] or method[2]
            args = method[3].strip()
            if args == 'THIS':
                argc = 1
            elif args.startswith('THIS_') and '(' not in args and ')' not in args:
                argc = 1 + len(args.removeprefix('THIS_').split(','))
            else:
                raise ValueError('unsupported parameter declaration: ' + args)
            methods.append((method_name, argc))
        if len(methods) != body.count('STDMETHOD') or not methods:
            raise ValueError('unparsed methods in ' + name)
        stale = set(binding['handlers']) - {method[0] for method in methods}
        if stale:
            raise ValueError('unknown handler methods in ' + name + ': ' + ', '.join(sorted(stale)))
        lines.append('static const uint8_t ' + symbol + '[16] = {')
        lines.append('    ' + ', '.join(f'0x{byte:02x}' for byte in iid) + ',')
        lines.extend(['};', 'static const ComMethod ' + table + '[] = {'])
        for method, argc in methods:
            handler = binding['handlers'].get(method, 'imports_unsupported')
            lines.append(f'    {{"{method}", {argc}, {handler}}},')
        lines.extend(['};', ''])
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--reference', type=Path, required=True)
    parser.add_argument('--bindings', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    try:
        generated = render(args.reference.read_bytes(), json.loads(args.bindings.read_text()))
        if args.check:
            if args.output.read_text() != generated:
                parser.error(str(args.output) + ' is stale; regenerate COM tables')
        else:
            if not args.output.exists() or args.output.read_text() != generated:
                args.output.write_text(generated)
    except (ValueError, OSError, KeyError) as failure:
        parser.error(str(failure))


if __name__ == '__main__':
    main()
