"""Writers for the generated tree: body chunks, entry thunks, funcs.h, table.c, symbols.json."""
import hashlib
import json
import os
import re
from collections import defaultdict
from pathlib import Path

from decoded import TranslateError

# Stable address buckets prevent an insertion from repacking the entire image.
# Oversize functions stand alone; recursively split only an over-budget bucket.
# SSA bodies are larger per guest instruction than decoded ones; at 512 KiB the
# median bucket chunk compiled in ~0.2 s, so per-file overhead dominated.
CHUNK_ADDRESS_BITS = 14
CHUNK_SOURCE_BUDGET = 2 * 1024 * 1024
ENTRY_ADDRESS_BITS = 16

BODY_HEADER = """/* generated -- translated bodies do not depend on replacement policy */
#ifndef RECOMP_BODY_H
#define RECOMP_BODY_H
#include "x86.h"
#include "intrinsics.h"
#include "seh.h"
#define RECOMP_ENTRY_CAT_(a, b) a##b
#define RECOMP_ENTRY_CAT(a, b) RECOMP_ENTRY_CAT_(a, b)
#define CALL_FN(a) RECOMP_ENTRY_CAT(entry_, a)(c)
#define CALL_FN_CHECKED(a, expected) RECOMP_ENTRY_CAT(entry_checked_, a)(c, expected)
#endif
"""


def partition_chunks(functions, bodies, budget=CHUNK_SOURCE_BUDGET):
    """Bound source size without moving functions outside their address bucket.

    The assignment is independent of input order and other buckets. A split can
    move neighbours within one 16 KiB guest-address bucket, never the whole image.
    Function bodies and their alternate-entry wrappers remain indivisible.
    """
    buckets = defaultdict(list)
    weights = {fn.addr: len("\n".join(bodies[fn.addr]).encode("utf-8")) + bool(bodies[fn.addr])
               for fn in functions}
    result = []
    for fn in sorted(functions, key=lambda fn: fn.addr):
        if weights[fn.addr] >= budget:
            result.append(("chunk_fn_%08x.c" % fn.addr, [fn]))
        else:
            buckets[fn.addr >> CHUNK_ADDRESS_BITS].append(fn)

    def split(group, base, bits):
        if sum(weights[fn.addr] for fn in group) <= budget or len(group) == 1:
            result.append(("chunk_%08x_%02d.c" % (base, bits), group))
            return
        half = base + (1 << (bits - 1))
        for children, start in (([fn for fn in group if fn.addr < half], base),
                                ([fn for fn in group if fn.addr >= half], half)):
            if children:
                split(children, start, bits - 1)

    for bucket, group in sorted(buckets.items()):
        split(group, bucket << CHUNK_ADDRESS_BITS, CHUNK_ADDRESS_BITS)
    return sorted(result)


def emit_body_chunks(out, functions, bodies, entries_by_fn):
    """Emit local call declarations: no global census, indices or overrides."""
    Path(out, "body.h").write_text(BODY_HEADER)
    paths = []
    call_pattern = re.compile(r"CALL_FN\(([0-9a-f]{8})\)")
    checked_pattern = re.compile(r"CALL_FN_CHECKED\(([0-9a-f]{8}),")
    for name, group in partition_chunks(functions, bodies):
        path = Path(out, name)
        text = {fn.addr: "\n".join(bodies[fn.addr]) for fn in group}
        calls = sorted({a for body in text.values() for a in call_pattern.findall(body)})
        checked = sorted({a for body in text.values() for a in checked_pattern.findall(body)})
        with path.open("w") as fh:
            fh.write('/* generated by tools/recomp/driver.py -- do not edit */\n')
            fh.write('#include "body.h"\n')
            for addr in calls:
                fh.write("void entry_%s(X86 *c);\n" % addr)
            for addr in checked:
                fh.write("void entry_checked_%s(X86 *c, uint32_t expected);\n" % addr)
            fh.write("\n")
            for fn in group:
                alt = sorted(entries_by_fn.get(fn.addr, ()))
                fh.write("/* %s  %d insns  %08x..%08x%s */\n"
                         % (fn.name, fn.count, fn.first, fn.last,
                            ("  entries: " + " ".join("%08x" % a for a in alt)) if alt else ""))
                fh.write(text[fn.addr] + "\n\n")
        paths.append(str(path))
    return paths


def emit_entry_chunks(out, entry_names, module=None, checked_returns=()):
    """Tiny address-named entry thunks own the changing dense dispatch indices.

    Native redirects are resolved only by table.c. Editing an override header
    therefore never recompiles either these thunks or the translated bodies.
    """
    groups = defaultdict(list)
    for index, addr in enumerate(entry_names):
        groups[addr >> ENTRY_ADDRESS_BITS].append((index, addr))
    paths = []
    for bucket, entries in sorted(groups.items()):
        path = Path(out, "chunk_entries_%08x.c" % (bucket << ENTRY_ADDRESS_BITS))
        with path.open("w") as fh:
            # Thunks never inspect CPU state; edits to inline instruction
            # helpers must not invalidate them along with the actual bodies.
            fh.write('/* generated stable entry thunks -- do not edit */\n'
                     '#include <stdint.h>\ntypedef struct X86 X86;\n')
            enter = "recomp_enter_%s" % module["key"] if module else "recomp_enter"
            fh.write("void %s(X86 *c, uint32_t index);\n" % enter)
            for index, addr in entries:
                fh.write("void entry_%08x(X86 *c) { %s(c, %du); }\n" % (addr, enter, index))
            checked = [(i, a) for i, a in entries if a in checked_returns]
            if checked:
                fh.write("void recomp_enter_checked(X86 *c, uint32_t index, uint32_t expected, "
                         "void (*body)(X86 *, uint32_t));\n")
                for index, addr in checked:
                    fh.write("void fn_checked_%08x(X86 *c, uint32_t expected);\n" % addr)
                    fh.write("void entry_checked_%08x(X86 *c, uint32_t expected) { "
                             "recomp_enter_checked(c, %du, expected, fn_checked_%08x); }\n"
                             % (addr, index, addr))
        paths.append(str(path))
    return paths


def emit_entry_dispatch():
    """The call-site policy, compiled once per image.

    Profiling still enters recomp_call (including module lookup and its frame
    watch). Raw/base tables bypass this seam for call-original and comparisons.
    A guest return address is already on the guest stack before entering here.
    The acquire flag load observes the installer's published callback pointer.
    """
    ordinary = """
void recomp_enter(X86 *c, uint32_t i)
{
    RecompSaved saved_; recomp_save(c, &saved_);
    if (recomp_profile_enabled) { recomp_call(c, recomp_func_addrs[i]); return; }
    recomp_execution_checkpoint(c);
#ifndef RECOMP_NO_HOOKS
    if (__builtin_expect(__atomic_load_n(&recomp_hooked[i], __ATOMIC_ACQUIRE) != 0u, 0)) {
        /* A hook callback observes the full register file, so a pending lazy
         * descriptor must be materialised before it runs.  The callee's own
         * entry settle may have been elided. */
        x86_cc_settle(c);
        recomp_hook_ptrs[i](c, i);
    } else
#endif
        recomp_base_ptrs[i](c);
#ifndef RECOMP_NO_HOOKS
    if (recomp_frame_watch)
        recomp_check_saved(c, recomp_func_addrs[i], &saved_);
#endif
}
"""
    checked = ordinary.replace("void recomp_enter(X86 *c, uint32_t i)",
                               "void recomp_enter_checked(X86 *c, uint32_t i, uint32_t expected, "
                               "void (*body)(X86 *, uint32_t))")
    checked = checked.replace("        recomp_base_ptrs[i](c);",
                              "        if (recomp_base_ptrs[i] == recomp_raw_ptrs[i]) body(c, expected);\n"
                              "        else recomp_base_ptrs[i](c);")
    return ordinary + checked


def write_funcs_header(out, entry_names):
    with open(os.path.join(out, "funcs.h"), "w") as fh:
        fh.write("/* generated by tools/recomp/driver.py -- do not edit */\n")
        fh.write("#ifndef RECOMP_FUNCS_H\n#define RECOMP_FUNCS_H\n")
        fh.write('#include "x86.h"\n#include "intrinsics.h"\n#include "seh.h"\n')
        fh.write("/* Define FN_<addr> in RECOMP_OVERRIDE_HEADER to select a native\n"
                 " * base in table.c. Stable entries route direct and computed calls\n"
                 " * through that selection without recompiling their callers. */\n")
        fh.write("#ifdef RECOMP_OVERRIDE_HEADER\n#include RECOMP_OVERRIDE_HEADER\n#endif\n")
        fh.write("#define FN_CAT_(a, b) a##b\n#define FN_CAT(a, b) FN_CAT_(a, b)\n")
        fh.write("#define FN(a) FN_CAT(FN_, a)\n")
        fh.write("#define FIDX(a) FN_CAT(FIDX_, a)\n")
        fh.write('#include "body.h"\n')
        for i, a in enumerate(entry_names):
            fh.write("#define FIDX_%08x %du\n" % (a, i))
        # Both spellings are declared: fn_ADDR because the chunk defines it,
        # and FN(ADDR) so an override header only has to #define FN_<addr> and
        # its replacement is declared here.  In the default case the two are
        # the same declaration, which C allows to repeat.
        for a in entry_names:
            fh.write("#ifndef FN_%08x\n#define FN_%08x fn_%08x\n#endif\n" % (a, a, a))
        for a in entry_names:
            fh.write("void fn_%08x(X86 *c);\nvoid FN(%08x)(X86 *c);\nvoid entry_%08x(X86 *c);\n" % (a, a, a))
        fh.write("#endif\n")


def write_table(out, entry_names, functions, call_returns):
    with open(os.path.join(out, "table.c"), "w") as fh:
        fh.write("/* generated by tools/recomp/driver.py -- do not edit */\n")
        fh.write('#include <stdio.h>\n#include <stdlib.h>\n#include "funcs.h"\n#include "thunks.h"\n'
                 '#include "discovery.h"\n#include "interp.h"\n\n')
        fh.write("const uint32_t recomp_func_addrs[] = {\n")
        for a in entry_names:
            fh.write("    0x%08xu,\n" % a)
        fh.write("};\n")
        fh.write("const uint32_t recomp_func_count = %d;\n\n" % len(entry_names))
        fh.write("static const uint32_t recomp_call_returns[] = {\n")
        for a in call_returns or [0]:  # valid C storage even for a call-free image
            fh.write("    0x%08xu,\n" % a)
        fh.write("};\nstatic const uint32_t recomp_call_return_count = %d;\n\n" % len(call_returns))
        fh.write("static const char *const profile_names[] = {\n")
        for symbol in functions:
            fh.write("    %s,\n" % json.dumps(symbol["name"]))
        fh.write("};\n")
        fh.write("void (*const recomp_base_ptrs[])(X86 *) = {\n")
        for a in entry_names:
            fh.write("    FN(%08x),\n" % a)
        fh.write("};\n\n")
        fh.write("static void recomp_run_base(X86 *c, uint32_t i)\n"
                 "{\n    recomp_base_ptrs[i](c);\n}\n\n")
        # The untouched translations, beside the possibly-overridden ones: the
        # two differ exactly where this build defined an FN_<addr> override, so
        # the override set becomes a fact the binary states about itself.
        fh.write("void (*const recomp_raw_ptrs[])(X86 *) = {\n")
        for a in entry_names:
            fh.write("    fn_%08x,\n" % a)
        fh.write("};\n\n")
        fh.write("RecompHookFn recomp_hook_ptrs[] = {\n")
        for _a in entry_names:
            fh.write("    recomp_run_base,\n")
        fh.write("};\n")
        fh.write("uint8_t recomp_hooked[%d];\n\n" % len(entry_names))
        fh.write(emit_entry_dispatch())
        # O(1) call-return lookup: a bitset over the addresses' span, built
        # once at translation time. The binary search this replaces ran on
        # every guest RET (7.4% self in a windowed profile); the bitset is
        # one array read. recomp_call_returns stays emitted as the source of
        # truth the translator's differential test compares the bitset to.
        if call_returns:
            cr_min = call_returns[0]
            cr_words = [0] * (((call_returns[-1] - cr_min) >> 5) + 1)
            for a in call_returns:
                off = a - cr_min
                cr_words[off >> 5] |= 1 << (off & 31)
        else:
            cr_min, cr_words = 0, [0]
        fh.write("static const uint32_t recomp_call_return_min = 0x%08xu;\n" % cr_min)
        fh.write("static const uint32_t recomp_call_return_bits[] = {\n")
        for w in cr_words:
            fh.write("    0x%08xu,\n" % w)
        fh.write("};\n")
        fh.write("""int recomp_is_call_return(uint32_t target)
{
    uint32_t off = target - recomp_call_return_min;
    if (target < recomp_call_return_min ||
        off >= (uint32_t)(sizeof recomp_call_return_bits / sizeof recomp_call_return_bits[0]) * 32u)
        return 0;
    return (recomp_call_return_bits[off >> 5] >> (off & 31)) & 1u;
}

const char *recomp_profile_name(uint32_t i) { return i < recomp_func_count ? profile_names[i] : 0; }

uint32_t recomp_override_count(void)
{
    uint32_t i, n = 0;
    for (i = 0; i < recomp_func_count; ++i)
        if (recomp_base_ptrs[i] != recomp_raw_ptrs[i]) ++n;
    return n;
}

uint64_t recomp_override_hash(void)
{
    uint64_t h = 1469598103934665603ull;
    uint32_t i, j;
    for (i = 0; i < recomp_func_count; ++i) {
        if (recomp_base_ptrs[i] == recomp_raw_ptrs[i]) continue;
        for (j = 0; j < 4; ++j) {
            h ^= (recomp_func_addrs[i] >> (8 * j)) & 0xffu;
            h *= 1099511628211ull;
        }
    }
    return h;
}

/* Indirect calls repeat the same few targets, so a direct-mapped cache sits
 * in front of the binary search. An entry is (target << 32) | (index + 2),
 * written as one word, so a racing reader sees an old or a new entry. */
static uint64_t recomp_lookup_cache[1u << 14];

static int32_t recomp_lookup_slow(uint32_t target);

static int32_t recomp_lookup(uint32_t target)
{
    uint32_t slot = (uint32_t)(target * 2654435761u) >> 18;
    uint64_t e = __atomic_load_n(&recomp_lookup_cache[slot], __ATOMIC_ACQUIRE);
    if ((uint32_t)(e >> 32) == target && (uint32_t)e)
        return (int32_t)((uint32_t)e - 2u); /* 1 caches "not a function" (a shim) */
    int32_t i = recomp_lookup_slow(target);
    __atomic_store_n(&recomp_lookup_cache[slot],
                     ((uint64_t)target << 32) | (uint64_t)(uint32_t)(i + 2), __ATOMIC_RELEASE);
    return i;
}

static int32_t recomp_lookup_slow(uint32_t target)
{
    uint32_t lo = 0, hi = recomp_func_count;
    while (lo < hi) {
        uint32_t mid = lo + (hi - lo) / 2;
        if (recomp_func_addrs[mid] < target) lo = mid + 1; else hi = mid;
    }
    return (lo < recomp_func_count && recomp_func_addrs[lo] == target)
           ? (int32_t)lo : -1;
}

int32_t recomp_index_of(uint32_t addr) { return recomp_lookup(addr); }

int recomp_thunk_target_kind(uint32_t target)
{
    if (recomp_lookup(target) >= 0 || recomp_module_lookup(target) >= 0) return 1;
    return (recomp_is_call_return(target) || recomp_module_is_call_return(target)) ? 2 : 0;
}

static void recomp_call_inner(X86 *c, uint32_t target);
void recomp_call(X86 *c, uint32_t target)
{
    // Unknown, indirect and shim targets read the guest's own flag fields.
    x86_cc_settle(c);
    RecompSaved saved_; recomp_save(c, &saved_);
    recomp_call_inner(c, target);
    if (recomp_frame_watch)
        recomp_check_saved(c, target, &saved_);
}
static void recomp_call_inner(X86 *c, uint32_t target)
{
    int32_t i = recomp_lookup(target);
    if (i >= 0) {
        recomp_execution_checkpoint(c);
        if (recomp_profile_enabled) recomp_profile_push((uint32_t)i);
#ifdef RECOMP_NO_HOOKS
        recomp_base_ptrs[i](c);
#else
        if (__atomic_load_n(&recomp_hooked[i], __ATOMIC_ACQUIRE))
            recomp_hook_ptrs[i](c, (uint32_t)i);
        else
            recomp_base_ptrs[i](c);
#endif
        if (recomp_profile_enabled) recomp_profile_pop();
        return;
    }
    if (recomp_module_call(c, target)) return;
    if (target >= GUEST_SHIM_BASE && target < GUEST_SHIM_END) {
        recomp_shim_call(c, target);
        return;
    }
    recomp_unknown_call(c, target);
}

/* Block-entry dispatch: the table holds every function start, every alternate
 * entry and every decoded jump-table target. */
void recomp_jump(X86 *c, uint32_t target)
{
    if (recomp_seh_pending_target()) recomp_seh_intercept(c, target);
    int32_t i = recomp_lookup(target);
    if (i >= 0) {
        recomp_execution_checkpoint(c);
        if (recomp_profile_enabled) recomp_profile_push((uint32_t)i);
#ifdef RECOMP_NO_HOOKS
        recomp_base_ptrs[i](c);
#else
        if (__atomic_load_n(&recomp_hooked[i], __ATOMIC_ACQUIRE)) {
            /* A jump into a hooked entry must publish a pending descriptor
             * before the callback reads the CPU. */
            x86_cc_settle(c);
            recomp_hook_ptrs[i](c, (uint32_t)i);
        } else {
            recomp_base_ptrs[i](c);
        }
#endif
        if (recomp_profile_enabled) recomp_profile_pop();
        return;
    }
    if (recomp_module_call(c, target)) return;
    if (target >= GUEST_SHIM_BASE && target < GUEST_SHIM_END) {
        recomp_shim_call(c, target);
        return;
    }
    if (recomp_is_call_return(target) || recomp_module_is_call_return(target)) { c->eip = target; return; }
    recomp_unknown_jump(c, target);
}

void recomp_unknown_jump(X86 *c, uint32_t target)
{
    if (recomp_run_thunk(c, target)) return;
    /* The address is code the map does not carry: record it (RECOMP_DISCOVERY)
     * so it can be added in Ghidra, then let the interpreter carry the run
     * past the gap so one run reports every gap it reaches. */
    discovery_note("jump", target, c->eip);
    if (interp_call(c, target)) return;
    discovery_write();
    fprintf(stderr, "recomp: no block entry for indirect jump to 0x%08x from 0x%08x\\n",
            target, c->eip);
    abort();
}
""")


def write_module_table(out, entry_names, functions, call_returns, module):
    key = module["key"]
    prefix = "recomp_%s_" % key
    with open(os.path.join(out, "table.c"), "w") as fh:
        fh.write('#include "funcs.h"\n#include "thunks.h"\n\n')
        fh.write("static const uint32_t %saddrs[] = {\n" % prefix)
        for addr in entry_names:
            fh.write("    0x%08xu,\n" % addr)
        fh.write("};\nstatic const uint32_t %sreturns[] = {\n" % prefix)
        for addr in call_returns or [0]:
            fh.write("    0x%08xu,\n" % addr)
        fh.write("};\nstatic const char *const %snames[] = {\n" % prefix)
        for symbol in functions:
            fh.write("    %s,\n" % json.dumps(symbol["name"]))
        fh.write("};\nstatic void (*const %sbase[])(X86 *) = {\n" % prefix)
        for addr in entry_names:
            fh.write("    FN(%08x),\n" % addr)
        fh.write("};\n")
        fh.write("static void %srun(X86 *c, uint32_t i) { %sbase[i](c); }\n" % (prefix, prefix))
        fh.write("static RecompHookFn %shooks[] = {\n" % prefix)
        for _ in entry_names:
            fh.write("    %srun,\n" % prefix)
        fh.write("};\nstatic uint8_t %shooked[%d];\n" % (prefix, len(entry_names)))
        fh.write("void recomp_enter_%s(X86 *c, uint32_t i)\n{\n" % key)
        fh.write("    RecompSaved saved_; recomp_save(c, &saved_);\n")
        fh.write("    recomp_execution_checkpoint(c);\n")
        fh.write("    if (recomp_profile_enabled) recomp_profile_push(i);\n")
        fh.write("    if (%shooked[i]) { x86_cc_settle(c); %shooks[i](c, i); }\n" % (prefix, prefix))
        fh.write("    else %sbase[i](c);\n" % prefix)
        fh.write("    if (recomp_profile_enabled) recomp_profile_pop();\n")
        fh.write("    if (recomp_frame_watch) recomp_check_saved(c, %saddrs[i], &saved_);\n}\n" % prefix)
        fh.write("static const RecompModule %smodule = {\n" % prefix)
        fh.write("    %s, 0x%08xu, 0x%08xu,\n" %
                 (json.dumps(module["name"]), module["base"], module["base"] + module["size"]))
        fh.write("    %saddrs, %d, %sbase, %shooks, %shooked,\n" %
                 (prefix, len(entry_names), prefix, prefix, prefix))
        fh.write("    %sreturns, %d, %snames\n};\n" % (prefix, len(call_returns), prefix))
        fh.write("__attribute__((constructor)) static void %sregister(void)\n" % prefix)
        fh.write("{\n    recomp_module_register(&%smodule);\n}\n" % prefix)


def write_symbols(out, executable, image_base, functions, curated):
    sha = hashlib.sha256(open(executable, "rb").read()).hexdigest()
    globals_out = []
    for section, body in sorted(curated.items()):
        if not section.startswith("globals."):
            continue
        e = {"name": section.split(".", 1)[1], "addr": "%08x" % body["addr"]}
        for k in ("size", "stride", "count"):
            if k in body:
                e[k] = body[k]
        globals_out.append(e)
    by_addr = {int(f["addr"], 16): f for f in functions}
    events = {k: "%08x" % v for k, v in sorted(curated.get("events", {}).items())}
    for name, addr in events.items():
        f = by_addr.get(int(addr, 16))
        if not f or not f["hookable"]:
            raise TranslateError("event %s (%s) is not a hookable entry symbol" % (name, addr))
    with open(os.path.join(out, "symbols.json"), "w") as fh:
        json.dump({"exe_sha256": sha, "image_base": "%08x" % image_base,
                   "functions": functions, "globals": globals_out,
                   "events": events}, fh, indent=1)
    return len(globals_out), len(events)


HOOK_EVIDENCE = ("reloc", "curated")


def hook_kind(addr, listed, alt_owner, provenance, evidence):
    """The symbol kind for `addr`, and whether a mod may hook it.

    Every entry can be dispatched to; only a place the program names has a
    meaning stable enough to hook:

      entry         a function start or a curated entry.
      block         an interior address a jump table names, however else it
                    is reached.
      alternate     an interior entry a base relocation or curation names.
      continuation  any other interior entry.
    """
    if addr in listed or "curated_entry" in evidence.get(addr, ()):
        return "entry", True
    if addr not in alt_owner or provenance.get(addr) == "table":
        return "block", False
    if any(e in HOOK_EVIDENCE for e in evidence.get(addr, ())):
        return "alternate", True
    return "continuation", False

